# Config file for compose, a tool that allows for easily managing multiple docker containers.
# https://docs.docker.com/compose/

services:
    surreal:
        # not :nightly because doing that once caused failures when graph linking
        # and also caused errors with query parameters (twice)
        image: surrealdb/surrealdb:v2.1.0
        ports:
            - 8000:8000
        restart: unless-stopped
        volumes:
            - ./data/surreal:/database
        command:
            - start
            - -l=trace
            - -u=root
            - -p=root
            - --allow-scripting
            - surrealkv://database

    economy:
        build: ./Economy
        ports:
            - 2009:2009
        restart: unless-stopped
        volumes:
            - ./data/economy:/economy/data
