version: "3"

# Config file for compose, a tool that allows for easily managing multiple docker containers.
# https://docs.docker.com/compose/

services:
    surreal:
        # not :nightly because doing that once caused failures when graph linking
        # and also caused errors with query parameters
        image: surrealdb/surrealdb:v1.2.0
        ports:
            - 8000:8000
        restart: unless-stopped
        volumes:
            - ./data/surreal:/database.db
        command:
            - start
            - --log=trace
            - --user=root
            - --pass=root
            - --allow-scripting
            - file:database.db
